In [5]:
import pandas as pd


df = pd.read_csv("./data/open-meteo-21.05N105.81E18m - open-meteo-21.05N105.81E18m.csv", skiprows=3)

df.head()

,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),cloud_cover (%),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_direction_10m (°),shortwave_radiation (W/m²)
0,2020-01-01 00:00,19.5,93,0.4,0.4,100,1024.1,1022.0,4.6,219,0.0
1,2020-01-01 01:00,19.4,93,0.3,0.3,100,1023.9,1021.8,4.6,252,0.0
2,2020-01-01 02:00,19.2,94,0.1,0.1,100,1023.4,1021.3,4.0,270,0.0
3,2020-01-01 03:00,19.1,94,0.1,0.1,100,1023.4,1021.2,3.1,306,0.0
4,2020-01-01 04:00,18.9,94,0.1,0.1,99,1023.3,1021.1,5.4,340,0.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   time                        52608 non-null  object
 1   temperature_2m (°C)         52608 non-null  float64
 2   relative_humidity_2m (%)    52608 non-null  int64
 3   precipitation (mm)          52608 non-null  float64
 4   rain (mm)                   52608 non-null  float64
 5   cloud_cover (%)             52608 non-null  int64
 6   pressure_msl (hPa)          52608 non-null  float64
 7   surface_pressure (hPa)      52608 non-null  float64
 8   wind_speed_10m (km/h)       52608 non-null  float64
 9   wind_direction_10m (°)      52608 non-null  int64
 10  shortwave_radiation (W/m²)  52608 non-null  float64
dtypes: float64(7), int64(3), object(1)
memory usage: 4.4+ MB

In [7]:
df.describe()

,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),cloud_cover (%),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_direction_10m (°),shortwave_radiation (W/m²)
count,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000
mean,24.246966,79.299859,0.254049,0.254049,73.788948,1011.160407,1009.071358,9.217687,139.593598,161.248479
std,5.552827,14.363258,1.062849,1.062849,36.604020,7.391028,7.341303,4.566850,96.411323,235.437590
min,6.500000,22.000000,0.000000,0.000000,0.000000,983.900000,981.900000,0.000000,1.000000,0.000000
25%,20.400000,70.000000,0.000000,0.000000,45.000000,1005.100000,1003.000000,5.800000,60.000000,0.000000
50%,25.100000,82.000000,0.000000,0.000000,99.000000,1010.700000,1008.600000,8.700000,135.000000,6.000000
75%,28.200000,91.000000,0.100000,0.100000,100.000000,1016.900000,1014.800000,12.100000,168.000000,274.000000
max,41.200000,100.000000,26.400000,26.400000,100.000000,1034.600000,1032.400000,60.700000,360.000000,949.000000

In [8]:
df["time"] = pd.to_datetime(df["time"])

In [9]:
df.head()

,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),cloud_cover (%),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_direction_10m (°),shortwave_radiation (W/m²)
0,2020-01-01 00:00:00,19.5,93,0.4,0.4,100,1024.1,1022.0,4.6,219,0.0
1,2020-01-01 01:00:00,19.4,93,0.3,0.3,100,1023.9,1021.8,4.6,252,0.0
2,2020-01-01 02:00:00,19.2,94,0.1,0.1,100,1023.4,1021.3,4.0,270,0.0
3,2020-01-01 03:00:00,19.1,94,0.1,0.1,100,1023.4,1021.2,3.1,306,0.0
4,2020-01-01 04:00:00,18.9,94,0.1,0.1,99,1023.3,1021.1,5.4,340,0.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   time                        52608 non-null  datetime64[ns]
 1   temperature_2m (°C)         52608 non-null  float64
 2   relative_humidity_2m (%)    52608 non-null  int64
 3   precipitation (mm)          52608 non-null  float64
 4   rain (mm)                   52608 non-null  float64
 5   cloud_cover (%)             52608 non-null  int64
 6   pressure_msl (hPa)          52608 non-null  float64
 7   surface_pressure (hPa)      52608 non-null  float64
 8   wind_speed_10m (km/h)       52608 non-null  float64
 9   wind_direction_10m (°)      52608 non-null  int64
 10  shortwave_radiation (W/m²)  52608 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(3)
memory usage: 4.4 MB

In [11]:
df.describe()

,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),cloud_cover (%),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_direction_10m (°),shortwave_radiation (W/m²)
count,52608,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000,52608.000000
mean,2022-12-31 23:30:00,24.246966,79.299859,0.254049,0.254049,73.788948,1011.160407,1009.071358,9.217687,139.593598,161.248479
min,2020-01-01 00:00:00,6.500000,22.000000,0.000000,0.000000,0.000000,983.900000,981.900000,0.000000,1.000000,0.000000
25%,2021-07-01 23:45:00,20.400000,70.000000,0.000000,0.000000,45.000000,1005.100000,1003.000000,5.800000,60.000000,0.000000
50%,2022-12-31 23:30:00,25.100000,82.000000,0.000000,0.000000,99.000000,1010.700000,1008.600000,8.700000,135.000000,6.000000
75%,2024-07-01 23:15:00,28.200000,91.000000,0.100000,0.100000,100.000000,1016.900000,1014.800000,12.100000,168.000000,274.000000
max,2025-12-31 23:00:00,41.200000,100.000000,26.400000,26.400000,100.000000,1034.600000,1032.400000,60.700000,360.000000,949.000000
std,NaN,5.552827,14.363258,1.062849,1.062849,36.604020,7.391028,7.341303,4.566850,96.411323,235.437590

In [12]:
df["target_temp"] = df["temperature_2m (°C)"].shift(-24)

In [13]:
df.head()

,time,temperature_2m (°C),relative_humidity_2m (%),precipitation (mm),rain (mm),cloud_cover (%),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_direction_10m (°),shortwave_radiation (W/m²),target_temp
0,2020-01-01 00:00:00,19.5,93,0.4,0.4,100,1024.1,1022.0,4.6,219,0.0,18.5
1,2020-01-01 01:00:00,19.4,93,0.3,0.3,100,1023.9,1021.8,4.6,252,0.0,18.6
2,2020-01-01 02:00:00,19.2,94,0.1,0.1,100,1023.4,1021.3,4.0,270,0.0,19.0
3,2020-01-01 03:00:00,19.1,94,0.1,0.1,100,1023.4,1021.2,3.1,306,0.0,19.0
4,2020-01-01 04:00:00,18.9,94,0.1,0.1,99,1023.3,1021.1,5.4,340,0.0,19.0

In [14]:
df = df.dropna()

In [15]:
from sklearn.model_selection import train_test_split

features = [
    "relative_humidity_2m (%)",
    "cloud_cover (%)",
    "wind_speed_10m (km/h)",
    "pressure_msl (hPa)",
    "precipitation (mm)"
]

# Training
X = df[features]
y = df["target_temp"]

split_index = int(len(df) * 0.8)

X_train = X[:split_index]
X_test = X[split_index:]

y_train = y[:split_index]
y_test = y[split_index:]

In [16]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [17]:
X.head()

,relative_humidity_2m (%),cloud_cover (%),wind_speed_10m (km/h),pressure_msl (hPa),precipitation (mm)
0,93,100,4.6,1024.1,0.4
1,93,100,4.6,1023.9,0.3
2,94,100,4.0,1023.4,0.1
3,94,100,3.1,1023.4,0.1
4,94,99,5.4,1023.3,0.1

In [18]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

# Predict
predictions = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)


print("MAE:", mae)
print("R²:", r2)

MAE: 2.2454945833729516
R²: 0.6940761744509328

In [19]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer


num_pipeline = make_pipeline(SimpleImputer(strategy="median"), StandardScaler())
preprocessing = ColumnTransformer([
    ("num", num_pipeline, features)
])

X_prepared = preprocessing.fit_transform(X)

In [20]:
X_prepared

array([[ 0.95393299,  0.71600436, -1.01082722,  1.75038416,  0.13719033],
       [ 0.95393299,  0.71600436, -1.01082722,  1.72332993,  0.04312309],
       [ 1.02355171,  0.71600436, -1.14220037,  1.65569438, -0.14501137],
       ...,
       [ 0.39698321,  0.71600436,  0.60944172,  0.33003744, -0.23907861],
       [ 0.6754581 ,  0.47017164,  0.32479988,  0.34356456, -0.23907861],
       [ 0.88431426,  0.66137487,  0.12774014,  0.35709167, -0.23907861]],
      shape=(52584, 5))

In [21]:
X_train_prepared = X_prepared[:split_index]
X_test_prepared = X_prepared[split_index:]

In [22]:
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit

num_pipeline = make_pipeline(
    SimpleImputer(strategy="median"),
    StandardScaler()
)

preprocessing = ColumnTransformer([
    ("num", num_pipeline, features)
])

tscv = TimeSeriesSplit(n_splits=3)

full_pipeline = Pipeline([
    ("preprocessing", preprocessing),
    ("random_forest", RandomForestRegressor(random_state=42)),
])

param_grid = [
    {
        "random_forest__n_estimators": [100, 200],
        "random_forest__max_depth": [10, 20, None],
        "random_forest__min_samples_leaf": [1, 2, 4],
        "random_forest__max_features": ["sqrt", 1.0],
    }
]

grid_search = GridSearchCV(
    full_pipeline,
    param_grid,
    cv=tscv,
    scoring="neg_root_mean_squared_error",
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 36 candidates, totalling 108 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('standardscaler',
                                                                                          StandardScaler())]),
                                                                         ['relative_humidity_2m '
                                                                          '(%)',
                                                                          'cloud_cover '
                                                                          '(%)',
                                                                          'wind_speed_10m '
                                                                          '(km/h)',
                                                                          'pressure_msl '
                                                                          '(hPa)',
                                                                          'precipitation '
                                                                          '(mm)'])])),
                                       ('random_forest',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid=[{'random_forest__max_depth': [10, 20, None],
                          'random_forest__max_features': ['sqrt', 1.0],
                          'random_forest__min_samples_leaf': [1, 2, 4],
                          'random_forest__n_estimators': [100, 200]}],
             scoring='neg_root_mean_squared_error', verbose=2)

In [23]:
final_model = grid_search.best_estimator_

feature_importances = final_model["random_forest"].feature_importances_
feature_importances.round(2)

array([0.11, 0.04, 0.03, 0.81, 0.01])

In [ ]:
final_predictions = final_model.predict(X_test)

mae = mean_absolute_error(y_test, final_predictions)
r2 = r2_score(y_test, final_predictions)


print("MAE:", mae)
print("R²:", r2)

MAE: 2.114937405900389
R²: 0.7282950175323484

In [28]:
final_model.predict(X_test.iloc[[0]])

array([26.98722323])

In [29]:
y_test.iloc[0]

np.float64(27.5)

In [31]:
# Looking for promise model before fine-tune

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
import pandas as pd
import time

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(random_state=42),
    "KNN": KNeighborsRegressor()
}

results = []

for name, model in models.items():
    pipe = Pipeline([
        ("preprocessing", preprocessing),
        ("model", model)
    ])

    start_time = time.time()
    pipe.fit(X_train, y_train)
    training_time = time.time() - start_time
    y_pred = pipe.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results.append({
        "Model": name,
        "RMSE": rmse,
        "MAE": mae,
        "R2": r2,
        "Training Time (s)": training_time
    })

results_df = pd.DataFrame(results).sort_values("RMSE")
results_df

               Model      RMSE       MAE        R2  Training Time (s)
3  Gradient Boosting  2.754754  2.109876  0.729783           3.742417
2      Random Forest  2.930260  2.245401  0.694255          18.759699
0  Linear Regression  2.993809  2.344239  0.680850           0.035909
4                KNN  3.068232  2.353384  0.664785           0.079300
1      Decision Tree  4.020724  3.076876  0.424354           0.307061

In [35]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform
tscv = TimeSeriesSplit(n_splits=3)


full_pipeline = Pipeline([
    ("preprocessing", preprocessing),
    ("gradient_boosting", GradientBoostingRegressor(random_state=42)),
])

param_distribs = {
    "gradient_boosting__n_estimators": randint(50, 300),
    "gradient_boosting__max_depth": randint(2, 6),
    "gradient_boosting__learning_rate": uniform(0.01, 0.19),
    "gradient_boosting__min_samples_leaf": randint(1, 20),
    "gradient_boosting__max_features": ["sqrt", 1.0],
}

rnd_search = RandomizedSearchCV(
    full_pipeline, 
    param_distributions=param_distribs, 
    n_iter=10, 
    cv=tscv,
    scoring='neg_root_mean_squared_error', 
    random_state=42)

rnd_search.fit(X_train, y_train)

RandomizedSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                   estimator=Pipeline(steps=[('preprocessing',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('simpleimputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('standardscaler',
                                                                                                StandardScaler())]),
                                                                               ['relative_humidity_2m '
                                                                                '(%)',
                                                                                'cloud_cover '
                                                                                '(%)',
                                                                                'wind_speed_10m '
                                                                                '(km/h)'...
                                        'gradient_boosting__max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D3A9DBF400>,
                                        'gradient_boosting__max_features': ['sqrt',
                                                                            1.0],
                                        'gradient_boosting__min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D3A9DE0250>,
                                        'gradient_boosting__n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000001D3A9DBE590>},
                   random_state=42, scoring='neg_root_mean_squared_error')

In [37]:
final_model = rnd_search.best_estimator_

feature_importances = final_model["gradient_boosting"].feature_importances_
feature_importances.round(2)

final_predictions = final_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, final_predictions))
mae = mean_absolute_error(y_test, final_predictions)
r2 = r2_score(y_test, final_predictions)


print("rmse:", rmse)
print("mae:", mae)
print("R²:", r2)

rmse: 2.757248059327576
mae: 2.1110026337893344
R²: 0.72929368454852